### ISSUE TITLE
CHANGE REQUEST: Owner Vs Active Keys.md

### ISSUE THREAD

**Issue by ALADINIO** [alacrityio/alacrity-support-documentation#10]
there is no documents are changing keys and how to generate keys @siliconswampio

**Comment by siliconswampio** [comment]
Technically with just the web app its not possible for common users to generate their own keys or change keys. Further more its difficult or perhaps even impossible for advanced users to generate, import or change keys using the alacrity cli tools in a way that will still allow them to access the alacrity login flow. The web app generates keys and Ciphers them with Salt + the users password. The Salt is hard coded into the front end code and is inaccessible to users. If a user creates an account outside of the front-end webapp he will be unable to properly cipher his key to work with the web app login process.

In the companion apps a user will be able to import, generate and change account keys and permissions.
